config/routes.rb
Rails.application.routes.draw do
  get '/top' => "homes#top"
  resources :lists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :image
  
  validates :title, presence: true
  validates :body, presence: true
  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      flash[:notice] = "投稿に成功しました。"
      redirect_to list_path(@list.id)
    else
      flash.now[:alert] = "投稿に失敗しました。"
      render :new
    end
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list= List.find(params[:id])
    list.update(list_params)
    redirect_to list_path(list.id)
  end

  def destroy
    list= List.find(params[:id])
    list.destroy
    redirect_to '/lists'
  end

  private
  def list_params
    params.require(:list).permit(:title, :body, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet"> 
 </head>

  <body>
    <header>
      <h1 class="headline">All Lists</h1>
    </header>
    <nav>
      <ul class="nav-list">
        <li class="nav-list-item">
          <%= link_to "Top", top_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "Lists", lists_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "New List", '/lists/new' %>
        </li>
      </ul>
    </nav>
    <main>
        <%= flash.each do |message_type, message| %>
          <div class="flash-message <%= message_type %>"><%= message %></div>
        <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>編集画面</h1>

<%= form_with model: @list do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit '保存' %>
<% end %>

app/views/lists/index.html.erb
<div class="list-wrap">
  <% @lists.each do |list|%>
  <div class="list-box">
    <% if list.image.attached? %>
      <%= image_tag list.image, size: "200x200" %>
    <% else %>
      <%= image_tag 'no_image', size: "200x200" %>
    <% end %>
    <div class="list-comment">
      <span class="list-body"><%= list.body %></span>
      <span class="list-title"><%= link_to list.title, list_path(list.id) %></span>
    </div>
  </div>
<% end %>
</div>

app/views/lists/new.html.erb
<h1>新規投稿</h1>

<% if @list.errors.any? %>
  <%= @list.errors.count %>件のエラーが発生しました
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model:@list, url: '/lists', method: :post do |f| %>
<h4>タイトル</h4>
  <%= f.text_field :title %>
<h4>本文</h4>
  <%= f.text_area :body%>
<h4>画像</h4>
  <%= f.file_field :image, accept: "image/*"%>

  <%= f.submit '投稿' %>
<%end%>

app/views/lists/show.html.erb
<h2>タイトル</h2>
<p><%= @list.title %></p>

<h2>本文</h2>
<p><%= @list.body %></p>

<h2>画像</h2>
   <%= image_tag @list.image, size: "300x300" %>

<%= link_to "編集", edit_list_path(@list.id) %>
<%= link_to "削除", list_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？"%>

<%= link_to "戻る", '/lists'%>